# coding=utf8

missions = {
    '大尺度_区域1_10m_高光谱':{
       'application': '生态',
        'aerocraft': '轻小型无人机(1)',
        'cameras': '高光谱相机(1)',
        'ground_resolution_m':10,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
    '大尺度_区域1_1m_双波段视频+可见光':{
       'application': '生态',
        'aerocraft': '轻小型无人机(79)',
        'cameras': '双波段视频(1)+可见光相机(78)',
        'ground_resolution_m':1,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
     '大尺度_区域1_10m_高光谱':{
       'application': '生态',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '高光谱相机(1)',
        'ground_resolution_m':10,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
     '大尺度_区域1_3.5m_偏振相机':{
       'application': '生态',
        'aerocraft': '轻小型固定翼无人机(3)',
        'cameras': '偏振相机(3)',
        'ground_resolution_m':3.5,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
    '大尺度_区域1_2.5m_多光谱相机':{
       'application': '生态',
        'aerocraft': '轻小型固定翼(2)+多旋翼无人机(1)',
        'cameras': '多光谱相机(3)',
        'ground_resolution_m':2.5,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
    '大尺度_区域1_1m_双波段视频+可见光相机':{
       'application': '生态',
        'aerocraft': '轻小型多旋翼无人机(20)',
        'cameras': '双波段视频(1)+可见光相机(19)',
        'ground_resolution_m':1,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
    '大尺度_区域1_0.8m_全色':{
       'application': '生态',
        'aerocraft': '轻小型多旋翼无人机(4)',
        'cameras': '全色相机(4)',
        'ground_resolution_m':0.8,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
    '大尺度_区域1_0.8m_全色':{
       'application': '生态',
        'aerocraft': '轻小型多旋翼无人机(4)',
        'cameras': '全色相机(4)',
        'ground_resolution_m':0.8,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3, 
    },
    '大尺度_区域1_0.1m': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '可见光视频相机',
        'ground_resolution_m': 0.3,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '中尺度_区域1_0.03m_可见光': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '可见光视频相机',
        'ground_resolution_m': 0.03,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '中尺度_区域1_0.05m_可见光': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '可见光视频相机',
        'ground_resolution_m': 0.05,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '中尺度_区域1_0.1m_可见光': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '可见光视频相机',
        'ground_resolution_m': 0.1,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '中尺度_区域1_0.3m_可见光': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '可见光视频相机',
        'ground_resolution_m': 0.3,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '中尺度_区域1_0.3m_红外': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '红外视频相机',
        'ground_resolution_m': 0.3,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '中尺度_区域2_4m_EOS450D': {
        'application': '洪涝',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': 'Canon EOS 450D',
        'ground_resolution_m': 4,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '小尺度_区域1_0.1m': {
        'application': '反恐',
        'aerocraft': '多旋翼无人机',
        'cameras': 'Canon EOS 450D',
        'ground_resolution_m': 0.1,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
    '小尺度_区域1_1m': {
        'application': '反恐',
        'aerocraft': '轻小型固定翼无人机',
        'cameras': '双波段视频吊舱',
        'ground_resolution_m': 1,
        'fly_east_west_direction': True,
        'forward_overlap': 0.6,
        'sideway_overlap': 0.3,
    },
}
